SNAPSHOT_INTERVAL_FRAMES = 15
MIN_DETECTION_SCORE = 0.40

BELLY_PERSIST_SECONDS = 2.0

AUDIO_COOLDOWN_SECONDS = 3.0

PIXELATE_BLOCK_SIZE = 20

HUD_COLOR_BGR = (0, 0, 200)
HUD_DIM_BGR = (0, 0, 120)
SCAN_LINE_ALPHA = 0.35
SCAN_LINE_SPEED = 3
WINDOW_TITLE = "CREEPER v1.0"

ASSET_DIR = "assets"
